# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'picker_config.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PickerConfig(object):
    def setupUi(self, PickerConfig):
        PickerConfig.setObjectName("PickerConfig")
        PickerConfig.resize(200, 551)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PickerConfig.sizePolicy().hasHeightForWidth())
        PickerConfig.setSizePolicy(sizePolicy)
        PickerConfig.setAutoFillBackground(False)
        PickerConfig.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.formLayout = QtWidgets.QFormLayout(PickerConfig)
        self.formLayout.setObjectName("formLayout")
        self.aberrationEnduranceL = QtWidgets.QLabel(PickerConfig)
        self.aberrationEnduranceL.setObjectName("aberrationEnduranceL")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.aberrationEnduranceL)
        self.aberrationEndurance = QtWidgets.QSpinBox(PickerConfig)
        self.aberrationEndurance.setObjectName("aberrationEndurance")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.aberrationEndurance)
        self.sceneAberrationThreshold = QtWidgets.QDoubleSpinBox(PickerConfig)
        self.sceneAberrationThreshold.setMaximum(1.0)
        self.sceneAberrationThreshold.setSingleStep(0.1)
        self.sceneAberrationThreshold.setObjectName("sceneAberrationThreshold")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sceneAberrationThreshold)
        self.line = QtWidgets.QFrame(PickerConfig)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.faceBestSizeL = QtWidgets.QLabel(PickerConfig)
        self.faceBestSizeL.setObjectName("faceBestSizeL")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.faceBestSizeL)
        self.faceBestSize = QtWidgets.QDoubleSpinBox(PickerConfig)
        self.faceBestSize.setMinimum(0.0)
        self.faceBestSize.setMaximum(1.0)
        self.faceBestSize.setSingleStep(0.01)
        self.faceBestSize.setObjectName("faceBestSize")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.faceBestSize)
        self.faceMaxSizeL = QtWidgets.QLabel(PickerConfig)
        self.faceMaxSizeL.setObjectName("faceMaxSizeL")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.faceMaxSizeL)
        self.faceMaxSize = QtWidgets.QDoubleSpinBox(PickerConfig)
        self.faceMaxSize.setMaximum(1.0)
        self.faceMaxSize.setSingleStep(0.1)
        self.faceMaxSize.setObjectName("faceMaxSize")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.faceMaxSize)
        self.faceExtendFactorL = QtWidgets.QLabel(PickerConfig)
        self.faceExtendFactorL.setObjectName("faceExtendFactorL")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.faceExtendFactorL)
        self.faceExtendFactor = QtWidgets.QDoubleSpinBox(PickerConfig)
        self.faceExtendFactor.setMinimum(1.0)
        self.faceExtendFactor.setMaximum(3.0)
        self.faceExtendFactor.setSingleStep(0.1)
        self.faceExtendFactor.setObjectName("faceExtendFactor")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.faceExtendFactor)
        self.line_2 = QtWidgets.QFrame(PickerConfig)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.line_2)
        self.line_3 = QtWidgets.QFrame(PickerConfig)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.line_3)
        self.faceSizeFactorL = QtWidgets.QLabel(PickerConfig)
        self.faceSizeFactorL.setObjectName("faceSizeFactorL")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.faceSizeFactorL)
        self.faceSizeFactor = QtWidgets.QDoubleSpinBox(PickerConfig)
        self.faceSizeFactor.setMaximum(10.0)
        self.faceSizeFactor.setSingleStep(0.1)
        self.faceSizeFactor.setObjectName("faceSizeFactor")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.faceSizeFactor)
        self.faceShapeFactorL = QtWidgets.QLabel(PickerConfig)
        self.faceShapeFactorL.setObjectName("faceShapeFactorL")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.faceShapeFactorL)
        self.faceShapeFactor = QtWidgets.QDoubleSpinBox(PickerConfig)
        self.faceShapeFactor.setMaximum(10.0)
        self.faceShapeFactor.setSingleStep(0.1)
        self.faceShapeFactor.setObjectName("faceShapeFactor")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.faceShapeFactor)
        self.faceAberrationFactorL = QtWidgets.QLabel(PickerConfig)
        self.faceAberrationFactorL.setObjectName("faceAberrationFactorL")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.faceAberrationFactorL)
        self.faceAberrationFactor = QtWidgets.QDoubleSpinBox(PickerConfig)
        self.faceAberrationFactor.setMaximum(1.0)
        self.faceAberrationFactor.setSingleStep(0.1)
        self.faceAberrationFactor.setObjectName("faceAberrationFactor")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.faceAberrationFactor)
        self.faceReforceFactorL = QtWidgets.QLabel(PickerConfig)
        self.faceReforceFactorL.setObjectName("faceReforceFactorL")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.faceReforceFactorL)
        self.faceReforceFactor = QtWidgets.QDoubleSpinBox(PickerConfig)
        self.faceReforceFactor.setMinimum(1.0)
        self.faceReforceFactor.setMaximum(10.0)
        self.faceReforceFactor.setSingleStep(0.1)
        self.faceReforceFactor.setObjectName("faceReforceFactor")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.faceReforceFactor)
        self.faceLeftFactorL = QtWidgets.QLabel(PickerConfig)
        self.faceLeftFactorL.setObjectName("faceLeftFactorL")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.faceLeftFactorL)
        self.faceTopFactorL = QtWidgets.QLabel(PickerConfig)
        self.faceTopFactorL.setObjectName("faceTopFactorL")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.faceTopFactorL)
        self.faceLeftFactor = QtWidgets.QDoubleSpinBox(PickerConfig)
        self.faceLeftFactor.setMinimum(-10.0)
        self.faceLeftFactor.setMaximum(10.0)
        self.faceLeftFactor.setSingleStep(0.1)
        self.faceLeftFactor.setObjectName("faceLeftFactor")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.faceLeftFactor)
        self.faceTopFactor = QtWidgets.QDoubleSpinBox(PickerConfig)
        self.faceTopFactor.setMinimum(-10.0)
        self.faceTopFactor.setMaximum(10.0)
        self.faceTopFactor.setSingleStep(0.1)
        self.faceTopFactor.setObjectName("faceTopFactor")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.faceTopFactor)
        self.faceMinSizeL = QtWidgets.QLabel(PickerConfig)
        self.faceMinSizeL.setObjectName("faceMinSizeL")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.faceMinSizeL)
        self.faceMinSize = QtWidgets.QDoubleSpinBox(PickerConfig)
        self.faceMinSize.setDecimals(3)
        self.faceMinSize.setMaximum(1.0)
        self.faceMinSize.setSingleStep(0.01)
        self.faceMinSize.setObjectName("faceMinSize")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.faceMinSize)
        self.sceneAberrationThresholdL = QtWidgets.QLabel(PickerConfig)
        self.sceneAberrationThresholdL.setObjectName("sceneAberrationThresholdL")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sceneAberrationThresholdL)
        self.actionAberrationThresholdL = QtWidgets.QLabel(PickerConfig)
        self.actionAberrationThresholdL.setObjectName("actionAberrationThresholdL")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.actionAberrationThresholdL)
        self.actionAberrationThreshold = QtWidgets.QDoubleSpinBox(PickerConfig)
        self.actionAberrationThreshold.setDecimals(4)
        self.actionAberrationThreshold.setMaximum(1.0)
        self.actionAberrationThreshold.setSingleStep(0.0001)
        self.actionAberrationThreshold.setObjectName("actionAberrationThreshold")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.actionAberrationThreshold)

        self.retranslateUi(PickerConfig)
        QtCore.QMetaObject.connectSlotsByName(PickerConfig)

    def retranslateUi(self, PickerConfig):
        _translate = QtCore.QCoreApplication.translate
        PickerConfig.setWindowTitle(_translate("PickerConfig", "Form"))
        self.aberrationEnduranceL.setText(_translate("PickerConfig", "色差忍耐值："))
        self.faceBestSizeL.setText(_translate("PickerConfig", "面部标准大小："))
        self.faceMaxSizeL.setText(_translate("PickerConfig", "面部上限大小："))
        self.faceExtendFactorL.setText(_translate("PickerConfig", "面部扩展系数："))
        self.faceSizeFactorL.setText(_translate("PickerConfig", "面部大小权重："))
        self.faceShapeFactorL.setText(_translate("PickerConfig", "面部形状权重："))
        self.faceAberrationFactorL.setText(_translate("PickerConfig", "面部色差系数："))
        self.faceReforceFactorL.setText(_translate("PickerConfig", "面部加强系数："))
        self.faceLeftFactorL.setText(_translate("PickerConfig", "面部左方权重："))
        self.faceTopFactorL.setText(_translate("PickerConfig", "面部上方权重："))
        self.faceMinSizeL.setText(_translate("PickerConfig", "面部下限大小："))
        self.sceneAberrationThresholdL.setText(_translate("PickerConfig", "场景色差阈值："))
        self.actionAberrationThresholdL.setText(_translate("PickerConfig", "动作色差阈值："))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PickerConfig = QtWidgets.QFrame()
    ui = Ui_PickerConfig()
    ui.setupUi(PickerConfig)
    PickerConfig.show()
    sys.exit(app.exec_())

