#!/usr/bin/python3
# -*- coding: utf-8 -*-

TMP_PATH = 'temp'
PICK_NAME = 'pick'
IMAGE_NAME = 'image'
FACE_NAME = 'face'
COLLECT_NAME = u'精简'
NORMALIZE_SCALE = 0.125
SAME_SCENE_THRESHOLD = 0.1
SAME_ACTION_THRESHOLD = 0.8
SAMPLE_IMAGE_NUM = 5
COMPARE_IMAGE_NUM = 3
