#!/usr/bin/python3
# -*- coding: utf-8 -*-

TMP_PATH = 'temp'
PICK_NAME = 'pick'
IMAGE_NAME = 'image'
FACE_NAME = 'face'
COLLECT_NAME = 'Simple'
ALL_NAME = 'All'
NORMALIZE_SCALE = 0.125
SAME_SCENE_THRESHOLD = 0.2
SAME_ACTION_THRESHOLD = 0.85
SAME_ACTION_EXTEND = 15
SAMPLE_IMAGE_NUM = 5
COMPARE_IMAGE_NUM = 3
